## Importing Necessary Libraries (Pandas, Numpy, Matplotlib)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import dataset and Separate data into feature and labels

In [2]:
data = pd.read_csv(filepath_or_buffer='data.csv')
feature = data.drop(labels='Purchased',axis=1).to_numpy()
label = data.iloc[:,-1].to_numpy()
feature

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [3]:
label

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Treating Missing Data in Dataset

In [4]:
from sklearn.impute import SimpleImputer

miss_treat = SimpleImputer(
    missing_values=np.nan,
    strategy="mean",
)
miss_treat.fit(feature[:, 1:3]) # fit data values to fit the model
feature[:, 1:3] = miss_treat.transform(feature[:, 1:3]) # replace the values of missing values to obtained value

feature

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding Categorical Data i.e String columns to numbers

### Independent variable

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

column_transform = ColumnTransformer(
    transformers=[('encode',OneHotEncoder(), [0])],
    remainder='passthrough'
)
feature = column_transform.fit_transform(feature)
feature

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

### dependent variable

In [6]:
from sklearn.preprocessing import LabelEncoder

label_en = LabelEncoder()
label = label_en.fit_transform(label)
label

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Split Data in Train and Test datasets

In [7]:
from sklearn.model_selection import train_test_split

feature_train, feature_test, label_train, label_test = train_test_split(
    feature,
    label,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

## Feature Scaling (Normalizing large values which makes other values ignored)

In [8]:
from sklearn.preprocessing import StandardScaler

normalize = StandardScaler(with_mean=True)
feature_train[:, 3:4] = normalize.fit_transform(feature_train[:,3:4])
feature_train[:, 4:5] = normalize.fit_transform(feature_train[:,4:5])
feature_train

array([[1.0, 0.0, 0.0, -0.7529426005471072, -0.6260377781240918],
       [1.0, 0.0, 0.0, 1.008453807952985, 1.0130429500553495],
       [1.0, 0.0, 0.0, 1.7912966561752484, 1.8325833141450703],
       [0.0, 1.0, 0.0, -1.7314961608249362, -1.0943465576039322],
       [1.0, 0.0, 0.0, -0.3615211764359756, 0.42765697570554906],
       [0.0, 1.0, 0.0, 0.22561095973072184, 0.05040823668012247],
       [0.0, 0.0, 1.0, -0.16581046438040975, -0.27480619351421154],
       [0.0, 0.0, 1.0, -0.013591021670525094, -1.3285009473438525]],
      dtype=object)