In [50]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [51]:
data = pd.read_csv('Data.csv')
feature = data.iloc[:,:-1].to_numpy()
label = data.iloc[:,-1].to_numpy()
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [52]:
from sklearn.model_selection import train_test_split

feature_train, feature_test, label_train, label_test = train_test_split(
    feature,
    label,
    test_size=0.2,
    random_state=np.random.randint(low=0, high=100, size=1)[0],
    shuffle=True
)

In [53]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly_model = PolynomialFeatures(degree=5)
feature_train_poly = poly_model.fit_transform(feature_train)

polyno_model = LinearRegression()
polyno_model.fit(feature_train_poly,label_train)
feature_train_poly

array([[1.00000000e+00, 2.75100000e+01, 6.37300000e+01, ...,
        2.95127391e+11, 1.93270351e+10, 1.26567136e+09],
       [1.00000000e+00, 2.24200000e+01, 6.25200000e+01, ...,
        2.61872687e+11, 1.62944494e+10, 1.01388611e+09],
       [1.00000000e+00, 2.75000000e+01, 6.53400000e+01, ...,
        1.10117256e+11, 5.14928614e+09, 2.40790123e+08],
       ...,
       [1.00000000e+00, 2.08400000e+01, 5.11900000e+01, ...,
        6.05350160e+11, 5.04803565e+10, 4.20957416e+09],
       [1.00000000e+00, 1.85000000e+01, 5.20800000e+01, ...,
        1.01523502e+12, 1.00985732e+11, 1.00450811e+10],
       [1.00000000e+00, 1.28800000e+01, 4.38000000e+01, ...,
        2.16988869e+11, 1.25503585e+10, 7.25896670e+08]])

In [54]:
polyno_model.predict(poly_model.fit_transform(feature_test))

array([434.11285036, 434.3526227 , 433.60865149, ..., 434.18467191,
       482.22814414, 446.71149596])

In [55]:
label_test

array([431.93, 433.19, 430.38, ..., 443.26, 480.53, 442.01])

In [56]:
from sklearn.metrics import r2_score

r2_score(y_true=label_test,y_pred=polyno_model.predict(poly_model.fit_transform(feature_test)))

0.9443859008995806