In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('Data.csv')
features = data.iloc[:,1:-1].to_numpy()
labels = data.iloc[:,-1].to_numpy()
features

array([[ 5,  1,  1, ...,  3,  1,  1],
       [ 5,  4,  4, ...,  3,  2,  1],
       [ 3,  1,  1, ...,  3,  1,  1],
       ...,
       [ 5, 10, 10, ...,  8, 10,  2],
       [ 4,  8,  6, ..., 10,  6,  1],
       [ 4,  8,  8, ..., 10,  4,  1]], dtype=int64)

In [3]:
from sklearn.impute import SimpleImputer

miss = SimpleImputer(
    missing_values=np.nan,
    strategy="mean",
)
features = miss.fit_transform(features)
features

array([[ 5.,  1.,  1., ...,  3.,  1.,  1.],
       [ 5.,  4.,  4., ...,  3.,  2.,  1.],
       [ 3.,  1.,  1., ...,  3.,  1.,  1.],
       ...,
       [ 5., 10., 10., ...,  8., 10.,  2.],
       [ 4.,  8.,  6., ..., 10.,  6.,  1.],
       [ 4.,  8.,  8., ..., 10.,  4.,  1.]])

In [4]:
from sklearn.model_selection import train_test_split

features_train,features_test,labels_train,labels_test = train_test_split(
    features,labels,random_state=0,test_size=0.2
)
features_train

array([[10.,  1.,  1., ...,  5.,  4.,  1.],
       [ 1.,  1.,  1., ...,  3.,  1.,  1.],
       [ 5.,  1.,  1., ...,  3.,  1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 3.,  1.,  1., ...,  2.,  1.,  1.],
       [10.,  9.,  7., ...,  7.,  7.,  1.]])

In [5]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
features_train = scale.fit_transform(features_train)
features_test = scale.fit_transform(features_test)
features_test

array([[-1.20834278, -0.72017241, -0.74303148, ..., -1.01206688,
        -0.57972754, -0.39273091],
       [-0.51569441, -0.72017241, -0.74303148, ..., -0.58280012,
        -0.57972754, -0.39273091],
       [ 0.17695396,  0.60417149,  0.57045643, ...,  0.27573339,
         0.12940347, -0.39273091],
       ...,
       [-0.16937022, -0.72017241, -0.74303148, ..., -1.01206688,
        -0.57972754, -0.39273091],
       [-0.16937022,  2.25960136,  0.24208445, ...,  2.42206718,
         2.611362  , -0.39273091],
       [-0.86201859, -0.72017241, -0.74303148, ..., -0.58280012,
        -0.57972754, -0.39273091]])

In [6]:
from sklearn.svm import SVC

model = SVC(kernel='rbf')
model.fit(features_train,labels_train)

SVC()

In [7]:
np.concatenate([
    model.predict(features_test).reshape(len(labels_test),1),
    labels_test.reshape(len(labels_test),1)
],axis=1)

array([[2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 2],
       [4, 4],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [4, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2,

In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix

conf = confusion_matrix(
    y_true=labels_test,
    y_pred=model.predict(features_test)
)
print(conf,"\nAccuracy : ",accuracy_score(
    y_true=labels_test,
    y_pred=model.predict(features_test)
))

[[82  5]
 [ 1 49]] 
Accuracy :  0.9562043795620438


In [9]:
features_train

array([[ 1.98839518, -0.69781134, -0.74152574, ...,  0.61907387,
         0.34532102, -0.33863738],
       [-1.22468404, -0.69781134, -0.74152574, ..., -0.18860673,
        -0.62157783, -0.33863738],
       [ 0.20335117, -0.69781134, -0.74152574, ..., -0.18860673,
        -0.62157783, -0.33863738],
       ...,
       [-1.22468404, -0.69781134, -0.74152574, ..., -0.99628733,
        -0.62157783, -0.33863738],
       [-0.51066644, -0.69781134, -0.74152574, ..., -0.59244703,
        -0.62157783, -0.33863738],
       [ 1.98839518,  1.90512627,  1.27779124, ...,  1.42675446,
         1.31221987, -0.33863738]])

In [10]:
scale.inverse_transform(features_train)

array([[10.23047852,  1.06753856,  1.00458546, ...,  4.7998301 ,
         3.60896378,  1.08646257],
       [ 0.95281513,  1.06753856,  1.00458546, ...,  2.91829471,
         0.88196739,  1.08646257],
       [ 5.07622108,  1.06753856,  1.00458546, ...,  2.91829471,
         0.88196739,  1.08646257],
       ...,
       [ 0.95281513,  1.06753856,  1.00458546, ...,  1.03675931,
         0.88196739,  1.08646257],
       [ 3.01451811,  1.06753856,  1.00458546, ...,  1.97752701,
         0.88196739,  1.08646257],
       [10.23047852,  8.92935637,  7.15406571, ...,  6.68136549,
         6.33596018,  1.08646257]])